2nd card game
I got the website to display cards and button below each cards and
for the first card I got the button to switch card from cardback to cardfront.

I got a message to display when use flips card and gets a jack
*error: gives error that text.toUpperCase (line 63) is not a function*
Need to do: Seperate buttons

later: add new game button, reduce turns left every time a button is clicked